### ISSUE TITLE
826CFB77: has no file mapping (original: 02 patched: 01)...skipping..

### ISSUE THREAD

**Issue by mrmaller1905** [emoose/idaxex#11]
Trying to patch Perfect Dark Zero XEX to enable 60 FPS but I get an error named "826CFB77: has no file mapping (original: 02 patched: 01)...skipping..". Can you add a feature to patch Xbox 360 XEXs?

**Comment by emoose** [comment]
Ah that's with IDA's patch function I'm guessing? haven't really added anything to support that yet, it'd probably be difficult for most XEXs since they're encrypted/compressed, but maybe something to let it work with unencrypted/uncompressed could be worth looking into.

For now you could use xextool to decompress/decrypt the xex (`xextool -eu -cu default.xex`), and then use xex1tool to convert the 826CFB77 addr to a file offset (`xex1tool -a 0x826CFB77 default.xex`), then open it in hex editor and change it there

btw how did you get IDA to try applying the patches to the file? was it something in `produce file`?

**Comment by mrmaller1905** [comment]
> btw how did you get IDA to try applying the patches to the file? was it something in `produce file`?

I won't apply patches with IDA "826CFB77: has no file mapping (original: 02 patched: 01)...skipping.." and "produce file" doesn't support XEXs.

**Comment by emoose** [comment]
Added support in 0d3e2bbd2503b45967b2aef7c81838baa7f1ed9d

If the XEX is both unencrypted & uncompressed the `Apply patches to input file` should work for most code/data in the file now, make sure to use `xextool -eu -cu default.xex` to decrypt/decompress it first.

Here's a release with it: https://github.com/emoose/idaxex/releases/tag/0.41
